# Generated by Django 5.1.1 on 2024-09-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_content_message_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_message',
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_reverse_message',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
