# Generated by Django 5.1 on 2024-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
