# Generated by Django 5.1 on 2024-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredentials",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
