# Generated by Django 5.1.1 on 2024-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_is_active_userprofile_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="", max_length=256),
        ),
    ]
