# Generated by Django 5.1.1 on 2024-09-17 14:45

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('last_active', models.DateTimeField(default=datetime.datetime.now)),
                ('bio', models.TextField(default='...', max_length=256)),
                ('avatar', models.ImageField(default=None, upload_to='avatars')),
                ('background', models.ImageField(default=None, upload_to='backgrounds')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
